### ISSUE TITLE
YAML Syntax Error in source/metadata.yml

### ISSUE THREAD

**Issue by chrisdaaz** [MariaPalacio2023/LanternTest1#1]
Hi Maria!

Thanks for working on this. I think we identified a need for some syntax rules early in the online tutorial. Your website is not building because of the double-quotes used in the subtitle field. Quotes and double quotes are tricky!

Here's how the subtitle field can be formatted in order to work:

```yaml
subtitle: |
    "That town is a red zone": Geographies of the Colombian
    Armed Conflict in 21st-Century Testimonial Narratives
```

This syntax uses the pipe literal block operator (`|`) to tell the YAML parser to pass everything that follows as is.
